"""Fail-closed loading of independently reviewed retry acceptance evidence.

A runtime flag is not a quality or contention test. Receipts are local deployment
artifacts, never accepted from an HTTP request, and cannot self-attest by naming
missing evidence files. No receipt is generated by this loader.
"""
import hashlib
import json
import math
from pathlib import Path


def load_acceptance(path, runtime_contract):
    if not path:
        return False, None, "acceptance_missing"
    if not isinstance(runtime_contract, dict) or not runtime_contract:
        return False, None, "runtime_not_accepted"
    try:
        source = Path(path).resolve(strict=True)
        if source.stat().st_size > 65536:
            return False, None, "acceptance_invalid"
        record = json.loads(source.read_text(encoding="utf-8"))
        if record.get("schema") != "rep-retry-acceptance/1" or record.get("runtime") != runtime_contract:
            return False, None, "runtime_not_accepted"
        evidence = record["evidence"]
        required = ("timing", "contention", "human_oracle")
        for name in required:
            entry = evidence[name]
            artifact = (source.parent / entry["file"]).resolve(strict=True)
            if (not artifact.is_relative_to(source.parent) or artifact == source
                    or hashlib.sha256(artifact.read_bytes()).hexdigest() != entry["sha256"]):
                return False, None, "acceptance_evidence_mismatch"
            if entry.get("verdict") != "PASS":
                return False, None, "acceptance_gate_open"
        if evidence["human_oracle"].get("kind") != "human_adjudicated_retry_content":
            return False, None, "human_oracle_missing"
        if (type(record.get("critical_content_losses")) is not int
                or record["critical_content_losses"] != 0
                or type(record.get("adjudicated_positive_cases")) is not int
                or record["adjudicated_positive_cases"] <= 0
                or type(record.get("hard_negative_cases")) is not int
                or record["hard_negative_cases"] <= 0):
            return False, None, "quality_not_accepted"
        measured = record.get("max_retry_e2e_ms")
        headroom = record.get("admission_headroom_ms")
        if any(type(value) not in (int, float) or not math.isfinite(value)
               for value in (measured, headroom)):
            return False, None, "headroom_unproven"
        if not 0 < measured < headroom < 2000 or record.get("max_slice_samples") != 160000:
            return False, None, "headroom_unproven"
        # R0/contention/oracle evidence admits R1 shadow; R1 cannot depend on its
        # own future PASS receipt. Only APPLY needs the final R1 evidence too.
        r1 = evidence.get("r1_shadow")
        if not isinstance(r1, dict) or r1.get("verdict") != "PASS":
            return False, headroom, "r1_shadow_pending"
        artifact = (source.parent / r1["file"]).resolve(strict=True)
        if (not artifact.is_relative_to(source.parent) or artifact == source
                or hashlib.sha256(artifact.read_bytes()).hexdigest() != r1["sha256"]):
            return False, None, "acceptance_evidence_mismatch"
        return True, headroom, "accepted"
    except (OSError, ValueError, KeyError, TypeError, AttributeError):
        return False, None, "acceptance_invalid"
